[package]
name = "cryptopals-rust"
version = "0.1.0"
authors = ["Erik J. Sturcke <erik@sturcke.dev>"]
edition = "2018"

[dependencies]
aes = "0.6.0"
base64 = "0.10.1"
hex = "0.3.2"
lazy_static = "1.4.0"
rand = "0.8.3"
tokio = { version = "1.4.0", features = ["full"] }
